# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Nickname.create(:column => 1, :word => 'Whip')
Nickname.create(:column => 1, :word => 'Beef')
Nickname.create(:column => 1, :word => 'Punt')
Nickname.create(:column => 1, :word => 'Splint')
Nickname.create(:column => 1, :word => 'Dick')
Nickname.create(:column => 1, :word => 'Smash')
Nickname.create(:column => 1, :word => 'Rick')
Nickname.create(:column => 1, :word => 'Fridge')
Nickname.create(:column => 1, :word => 'Stag')
Nickname.create(:column => 1, :word => 'Rod')
Nickname.create(:column => 1, :word => 'Thrush')
Nickname.create(:column => 1, :word => 'Butch')
Nickname.create(:column => 1, :word => 'Savage')
Nickname.create(:column => 1, :word => 'Thrust')
Nickname.create(:column => 1, :word => 'Touch')
Nickname.create(:column => 1, :word => 'Fist')

Nickname.create(:column => 2, :word => 'SquatThrust')
Nickname.create(:column => 2, :word => 'McBrothRun')
Nickname.create(:column => 2, :word => 'PlankSplint')
Nickname.create(:column => 2, :word => 'ManlyButt')
Nickname.create(:column => 2, :word => 'McFistSquat')
Nickname.create(:column => 2, :word => 'McLargeStag')
Nickname.create(:column => 2, :word => 'HackPec')
Nickname.create(:column => 2, :word => 'McNeckGnaw')
Nickname.create(:column => 2, :word => 'QuadsBlow')
Nickname.create(:column => 2, :word => 'AbsHair')
Nickname.create(:column => 2, :word => 'BrothLift')
Nickname.create(:column => 2, :word => 'ManTooth')
Nickname.create(:column => 2, :word => 'HardMeat')
Nickname.create(:column => 2, :word => 'VanderSmash')
Nickname.create(:column => 2, :word => 'HunkyBeef')
Nickname.create(:column => 2, :word => 'McSlamBulk')
Nickname.create(:column => 2, :word => 'SmackDown')
Nickname.create(:column => 2, :word => 'BuffMeat')
